version: "3.8"
services:
  redis:
    container_name: 'redis'
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  phpredisadmin:
    container_name: 'phpredisadmin'
    image: erikdubbelboer/phpredisadmin
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    restart: always
    depends_on:
      - redis
    ports:
      - "8081:80"

networks:
  backend:
    driver: bridge
